- hosts: localhost
  connection: local
  become: true
    
  tasks:  
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - vim
        - neofetch
        - syncthing
        - keepassxc
        - steam
            
  - name: Enable Flathub repository
    become: yes
    command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  - name: Install Flatpaks
    community.general.flatpak:
      name:
        - com.spotify.Client
        - com.getpostman.Postman
        - org.kde.kdenlive
        - com.slack.Slack
        - com.discordapp.Discord
        - com.microsoft.Teams
        - us.zoom.Zoom
        - org.signal.Signal
        - md.obsidian.Obsidian
        - com.github.tchx84.Flatseal
        - org.gimp.GIMP
        - com.visualstudio.code
        - org.flameshot.Flameshot

  - name: Install Snaps
    community.general.snap:
      name:
        - authy
        
  - name: Install nvm(node version manager)
    shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
