
- name: Enable Google Chrome repo
  become: yes
  command: dnf config-manager --set-enabled google-chrome

- name: Enable multimedia codecs
  become: yes
  command: dnf groupupdate Multimedia -y

- name: Enable audinux repo
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: ycollet/audinux/
      
- name: Enable DISTRHO repo
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: teervo/DISTRHO/
    
- name: Enable Dexed repo
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: audron/dexed

- name: install packages
  package:
    name:
      - google-chrome-stable
      - snapd
      - Cadence
      - surge
      - Rack-v2
      - vst-DISTRHO\*
      - dexed
      - lutris
