- name: Enable KXStudio Repos
  become: yes
  command: wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos_10.0.3_all.deb
    
- name: Install KXStudio Repos
  become: yes
  command: dpkg -i kxstudio-repos_10.0.3_all.deb
    
- name: Remove KXStudio Repos Installer
  become: yes
  command: rm kxstudio-repos_10.0.3_all.deb    
    
- name: install packages
  apt:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
      - apt-transport-https 
      - gpgv
      - helm
      - dexed
      - surge
    update_cache: yes
